Code Exchange upgrade
TwilioDevEd/verify-v2-quickstart-node pull request #60
Opened 2020-04-02 21:22 UTC by po5i

Resolves #59

2020-04-24 18:46 UTC, dkundel requested changes

2020-04-24 18:46 UTC, dkundel commented on README.md
> +      $ npx yarn
Can we swap this project to `npm` and have the npm install and start steps here for consistency?

2020-04-24 18:52 UTC, dkundel commented on package.json
>    "dependencies": {
When I run `npm install` I still get a lot of deprecated notifications. Can we make sure to clean those up as best as possible?

2020-04-24 18:52 UTC, dkundel requested changes
There's a Dockerfile that doesn't seem to actually work so I think it's worth removing that one

2020-04-28 22:05 UTC, rojasTob commented on package.json
>    "dependencies": {
Hi @dkundel . I got three warnings of deprecated libraries and regarding this:
1. The popper.js dependency was added on package.json file as peerDependencie for Bootstrap. I've reviewed the documentation about bootstrap/webpack and it seems to be needed (https://getbootstrap.com/docs/4.0/getting-started/webpack/).
2. The request and core-js dependencies are not defined on package.json file, but they are inner dependencies for Webpack.

In order to resolve those warnings, we could remove webpack / bootstrap from the app and refactor it, but it could take more time. What do you think?

2020-05-05 22:34 UTC, dkundel approved these changes

2020-05-13 13:16 UTC, merged